### ISSUE TITLE
Subdirs option results in "UserWarning: skipping file {}: file already exists"

### ISSUE THREAD

**Issue by xgorn** [jirassimok/dir2pdf#6]
I'm trying to the use package with --subdirs but seems like it didn't work, can you show me how it is actually working?

**Comment by jirassimok** [comment]
It looks like you're using `{}` as the entire PDF name argument. If you don't include anything else in the name or use a capturing group in the argument to `--subdir`, you'll get the error in the issue title, because the PDF file the program wants to write has the same name as the directory it's reading.

If the directories you want to read are `basedir/subdir_1`, `basedir/subdir_2`, and so on, I recommend using this tool like so:
```sh
dir2pdf --subdirs 'subdir_(.*)' 'dir-{}.pdf' basedir
```
This will give you PDFs named `dir-1.pdf`, `dir-2.pdf`, and so on.

(The `(.*)` capturing group in the `--subdirs` argument will capture everything after "subdir_", and it will be substituted into the PDF argument's format string.)
